### ISSUE TITLE
НЕ РАБОТАЕТ

### ISSUE THREAD

**Issue by Grumgog** [SooperOleg/IAE-Integible_Art_Engine#1]
НИЧЕ НЕ РОБОТАЕТ!!1 НИЧЕГО! ХОТЕЛ СОБРАТЬ - НЕ СОБРАЛОСЬ!! ЧТО ЗА ВЕЩИ ТАКИЕ ТВОРЯТСЯ!

**Comment by SooperOleg** [comment]
ВИРУСАМ НЕ МЕСТО НА ТАКОМ ПРИЛИЧНОМ САЙТЕ, ИЗЫДИ

**Comment by Grumgog** [comment]
IA N3 V1RУ2!
EXIT
